#!/bin/bash
#author:Mehmet Ümit Özden

bash_profile_path="$HOME/.bash_profile"
os="$(uname -s)"
case $os_name in
	'Linux')
		cpy='xclip -selection clipboard'
		;;
	'Darwin')
		cpy='pbcopy'
		;;
		*)
		cpy='clip'
		;;	
esac
mkdir -p "$HOME/.ssh"
ssh-keygen -t rsa -q -f "$HOME/.ssh/ssh_key" -N "" && echo "SSH key pair generated..." || echo "Error while generating ssh key pair!" | exit 1
cat "$HOME/.ssh/ssh_key.pub" | eval `cpy` && echo "Public key copied to clipboard..." || echo "Error while copying public key to clipboard!" | exit 1
ssh_command="eval \`ssh-agent\`; ssh-add $HOME/.ssh/ssh_key; fi"
echo $ssh_command >> $bash_profile_path
