#!/bin/bash
#author: Mehmet Ümit Özden

profile_path="$HOME/.bash_profile"
os="$(uname -s)"
eval_agent=true
case $os_name in
	'Linux')
		cpy='xclip -selection clipboard'
		;;
	'Darwin')
		cpy='pbcopy'
		;;
		*)
		cpy='clip'
		;;	
esac
mkdir -p "$HOME/.ssh"
ssh-keygen -t rsa -q -f "$HOME/.ssh/ssh_key" -N "" && echo "SSH key pair generated..." || echo "Error while generating ssh key pair!" | exit 1
cat "$HOME/.ssh/ssh_key.pub" | eval `cpy` && echo "Public key copied to clipboard..." || echo "Error while copying public key to clipboard!" | exit 1
if [ "$eval_agent" = true ]; then ssh_command="eval \`ssh-agent\`; ssh-add $HOME/.ssh/ssh_key; fi"; else ssh_command="ssh-add $HOME/.ssh/ssh_key"; fi
echo $ssh_command >> $profile_path
